[en]
  languageName = "English"
  baseURL = "https://juliaevseeva.github.io/Test-hugo"
  contentDir = "content/en"
  weight = 1
  [en.params]
    languageISO = "EN"

[ru]
  languageName = "Russian"
  baseURL = "https://juliaevseeva.github"
  contentDir = "content/ru"
  weight = 2
  [ru.params]
    languageISO = "RU"
