collections_config:
  careers:
    add_options:
      - name: Add new custom career
        schema: english
    schemas:
      english:
        path: schemas/test.md
  ru:
    add_options:
      - name: Добавить вакансию
        schema: default
