collections_config:
  pages:
    _enabled_editors:
      - visual
      - content
      - source
  ru:
    path: content/ru/careers
    add_options:
      - name: New test file
        schema: test
    schemas:
      test:
        path: schemas/test.md