collections_config:
  pages:
    _enabled_editors:
      - visual
      - content
      - source
  en:
    add_options:
      - name: New file
        schema: new
    schemas:
      new:
        path: schemas/schema_en.md
  ru:
    singular_name: Вакансия
    add_options:
      - name: New test file
        schema: test
    schemas:
      test:
        path: schemas/test_ru.md
_inputs:
  category:
    type: select
    options:
      values: _select_data.categories
      value_key: key
      text_key: display_name
_select_data:
  categories:
    - key: services
      display_name: Services
      name_ru: Сервисы
      name_ua: Сервіси
data_config:
  categories:
    path: data/categories.yml

