collections_config:
  careers:
    add_options:
      - name: Add New
        schema: default
  ru:
    add_options:
      - name: Добавить вакансию внутри career
        collection: careers
        schema: default