collections_config:
  pages:
    _enabled_editors:
      - visual
      - content
      - source
  ru:
    singular_name: Вакансия
    add_options:
      - name: New test file
        schema: test
    schemas:
      test:
        path: schemas/test.md
_inputs:
  title:
    comment: Some comment for the title
  offices:
    type: select
    options:
      values: offices
data_config:
  offices:
    # Reads the contents of each file in this directory
    path: data/authors.csv
