collections_config:
  pages:
    _enabled_editors:
      - visual
      - content
      - source
  en:
    add_options:
      - name: New file
        schema: new
    schemas:
      new:
        path: schemas/schema_en.md
  i18n:
    singular_name: Translation
    path: i18n
_inputs:
  category:
    type: multiselect
    options:
      values: data.options
      value_key: key
      text_key: display_name

data_config: true
