collections_config:
  careers:
    add_options:
      - name: Add New
        schema: default
  ru:
    careers:
      add_options:
        - name: Добавить вакансию внутри career
          schema: default