collections_config:
  pages:
    _enabled_editors:
      - visual
      - content
      - source
  ru:
    singular_name: Staff Member
    add_options:
      - name: New test file
        schema: test
    schemas:
      test:
        path: schemas/test.md
    _inputs:
      title:
        comment: Some comment for the title