baseURL = 'https://juliaevseeva.github.io'
languageCode = 'en-us'
title = 'Test website'
theme = 'my-theme'

defaultContentLanguage = 'en'

[taxonomies]
  direction = "direction"
  category = "category"
