name: Feature Teaser
description: Create or edit a feature teaser
title: "Create a feature teaser [teaser name]"
labels: ["🏠 Home", "teaser"]
projects: ["JxBrowser Content"]
assignees:
  - octocat
body:
  - type: textarea
    id: goal
    attributes:
      label: The goal of the task
      placeholder: 'Describe a feature teaser that you are going to add or edit'
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: The feature translation will be done
      options:
        - Within this task
        - In a separate task
      default: 0
  - type: markdown
    attributes:
      value: "## Checklist before releasing a teaser into production"
  - type: checkboxes
    id: image_checklist
    attributes:
      label: Feature image requirements
      options:
        - label: 'The font-family is [Pragmatica](https://drive.google.com/drive/folders/1as-BIQ4R1ArAx40-xQHSzBrLGc0cvXh1).'
        - label: 'The font-size of the body text is `15px`.'
        - label: 'The width of the image is `834px` if it is possible.'
        - label: 'The image is saved in `webp` format.'
        - label: 'The image file name is in lowercase and with hyphens to separate words. For example `4k-60fps-diagram.webp`.'
        - label: 'Added in `static/images/product-visuals/[product-name]/features/` folder and provided as `"image_path": "/images/product-visuals/jxbrowser/features/4k-60fps-diagram.webp"`.'
  - type: checkboxes
    id: configuration_checklist
    attributes:
      label: Feature teaser configuration
      options:
        - label: 'The teaser content is declared inside `"modal": {}`, allowing the teaser to be opened.'
        - label: 'All necessary image properties are configured: `image_path`, `image_alt`, `full_width`, `has_shadow`, `has_border_radius`.'
          description: |
            ```
            "image": {
              "test"
            }
            ```
        - label: 'The `hashtag` is added to open the feature via a link. The `hashtag` should be in English in lowercase style. For example `"hashtag": "html-css-javascript"` and should be the same for all feature translations.'
  - type: checkboxes
    id: release_checklist
    attributes:
      label: Teaser release
      options:
        - label: 'Spelling is correct.'
        - label: 'The feature teaser looks good upon window resizing.'
        - label: 'Looks good in Chrome, Safari, Firefox, iOS, Android.'
        - label: 'All links are leading where intended.'
